### ISSUE TITLE
Handle Multi-Account Containers extension

### ISSUE THREAD

**Issue by Korko** [rthaut/YouTubePopoutPlayer#104]
Mozilla Firefox have an official extension called Multi-Account Containers allowing to have "categories" of tabs each having their separate cookies and so possibly a different account on each. https://github.com/mozilla/multi-account-containers/#readme

By default, YouTubePopupPlayer opens a tab without a specific container. It may be very interesting to keep the container of the original tab if possible.

**Comment by rthaut** [comment]
This is a great idea for an enhancement; thank you for the recommendation.

I know that a different container extension was causing the popout to be closed immediately (see #64), so any container-related changes should probably go through some extensive testing.

Here are my notes (for myself or someone else) for implementation ideas based on my initial investigation:

> The [documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Work_with_contextual_identities) shows it is possible to open a new tab using a specific contextual identity (a.k.a. container), and it also appears to be possible to retrieve the contextual identity of the original/current tab.

> The only downside to this approach is the ["cookies" permission](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies) is needed to get/set the `cookieStoreId` property on tabs. Ideally this could be an optional permission for the Firefox build that is only requested when users "opt in" to enabling container support (likely via a new FF-only toggle switch on the Options panel), as I think many users would be apprehensive of using/updating the extension if the "cookies" permission was always required.

> Alternatively, there might be a different way to open the popout so that the container extension(s) intercept the popout and handle it directly (like they do when clicking links on webpages within a container). However, based on the multitude of issues I ran into with other opening approaches during the version 3 rewrite, I'm fairly certain this won't be possible.
