### ISSUE TITLE
Always on top

### ISSUE THREAD

**Issue by danieljcpsilva** [rthaut/YouTubePopoutPlayer#17]
Hi, is there a way to put a video playing in youtubepopoutplayer for firefox but in "always on top" mode?

That way we can see the video and work in other issues at the same time.

Thanks
Daniel Silva

**Comment by rthaut** [comment]
As of now there is no way to set a window to be "always on top" through the browser extension APIs.

This can be accomplished with additional software, though, so I have documented that (at least a little) on the [FAQ page](http://rthaut.github.io/YouTubePopoutPlayer/faq) of the new documentation site.

I am closing this issue for now, but if the APIs ever expose functionality for setting a window to always be on top, then this request can be revisited.
