### ISSUE TITLE
Autoplay is not working

### ISSUE THREAD

**Issue by carrageen** [rthaut/YouTubePopoutPlayer#18]
`?start=..&autoplay=1` is in the URL but autoplay isn't working.

Using latest Firefox (60.0.2) on Windows 10.

Here's a screenshot of the embedded window.
https://lambda.sx/Wnx.png
![wnx 1](https://user-images.githubusercontent.com/19150352/41498349-a8f00e64-716b-11e8-95f9-92427bd9fcf4.png)

**Comment by rthaut** [comment]
@carrageen I have not been able to reproduce this yet.

The `autoplay` parameter should simply start the video immediately when the popup opens (so long as the video is not at the end). I have had some users confused, expecting that to automatically loop the video (which this does NOT do), so I just want to make sure your understanding is correct.

Also note that is native YouTube functionality, not anything added by the extension.
