### ISSUE TITLE
Configurable Window/Player Size

### ISSUE THREAD

**Issue by rthaut** [rthaut/YouTubePopoutPlayer#21]
Create a configurable setting to allow users to determine the size of the popout player.

Options/functionality must include:
* Use current video size (this is the current functionality)
* Use specified video size
    * Provide width x height input fields
        * These fields could be either pixels or percentages

For user convenience, the width and height inputs should probably indicate or suggest values that are "standard" aspect ratios.

Additionally/alternatively, there could be an option for common sizes, where selecting that option presents a dropdown menu of various pre-configured sizes.

Possible issues:
* If the setting uses sync storage, then the size a user sets on one device might not be appropriate for another (ex: setting a large resolution on a desktop, then using a laptop with a low resolution)
* How would this function if #20 is implemented? Presumably the size setting would be ignored, but on the UI the setting(s) should probably be completely disabled to avoid confusion.
    * Alternatively, the window could open a "wrapper" page that allows the user to resize the video player (without resizing the window), and it could be set initially to the configured size.

**Comment by rthaut** [comment]
[Here's a mockup for the Options page](https://codepen.io/rthaut/full/xmWydM) that covers handling #20 and #21.

The mockup uses AngularJS to drive the dynamic elements of the form, and Bootstrap 4 for styling/layout. I know AngularJS can be used on the options page, but since it is rendered within a browser page for the extension (rather than being a dedicated page of its own), i'm not sure if there will be any issues using Bootstrap.

**Comment by d5c4b3** [comment]
> How would this function if #20 is implemented?

Is it possible to have a right click menu on the popout button? If it is possible you could make it so that right clicking gives you the option to open in new tab, or middle clicking (with the scroll wheel) automatically does that. This also removes the need to have it be a configurable option.
