### ISSUE TITLE
Playlist Videos in Popout Player do not Automatically Advance

### ISSUE THREAD

**Issue by Belgian-Coder** [rthaut/YouTubePopoutPlayer#323]
### Steps to reproduce
1. Create a playlist with at least 2 videos
2. Select and play the playlist
3. Open current video in Popout player
4. Watch or skip video till the end

### Version
Chrome extension YouTube Popout Player version 3.1.1

### Expected
- After opening in popout player and finishing the active video, the next video in the playlist will start playing in the same window
- Controls for skipping to previous or next video are visible in pop out player

### Addendum
I went through the existing tickets and found that this functionality was merged in version 2.1.0. My guess is that it broke due to changes on YouTube or the extension code

**Comment by rthaut** [comment]
Thanks for the detailed report, and for the due diligence on reviewing old tickets!

I am not able to reproduce this issue. I tested using a fresh install of Chrome Version 88.0.4324.182 (Official Build) (64-bit) and YouTube Popout Player version 3.1.1 with the default settings. I used this playlist to test: https://www.youtube.com/playlist?list=PLRnHcRQUxuofeHfr6wSWHImNl7Hthj0BQ

When I play the first video in that playlist in the Popout Player, it successfully moves to the second video as expected, both when I watch the entire first video all the way through, and when I skip to near the end of the first video.

Can you provide the URL to the playlist you are testing with? Also, do you have any other extensions installed in Chrome?

**Comment by Belgian-Coder** [comment]
Just checked and I found the culprit. The playlist was listed as private. Apparently, YouTube does not allow to embed private playlists, I can see the logic in that. Sorry for taking up your time.
