### ISSUE TITLE
Chrome: All videos now say "unavailable" in pop-out window

### ISSUE THREAD

**Issue by 340829762948305** [rthaut/YouTubePopoutPlayer#356]
Chrome Version 92.0.4515.159 (Official Build) (64-bit)

**Comment by rthaut** [comment]
It looks like the `Referer` header is not actually being set in Chrome. This is most likely due to needing to add the [`extraHeaders` option for Chrome 72+](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/vYIaeezZwfQ).
