### ISSUE TITLE
On v.4.1.0, can't use left/right arrow keys to jump back/forward?

### ISSUE THREAD

**Issue by mQkatz** [rthaut/YouTubePopoutPlayer#368]
I love this extension, so I just upgraded to 4.1.0 on faith. The full-screen option works, but with the player popped out, I've now lost the ability to use my left/right arrow keys to scrub backward and forward in the video. They now do nothing. Is this a known issue?

Previously, they did jump back and forward – although by coarser intervals than YouTube's native 5 seconds per press. (It felt like ~15 seconds.) Ideally, the mini-player would match YouTube's 5-second behavior for these 2 keys.

This is on Firefox 73.0.1, on Mac OS 10.13.6. Please don't judge either of those versions – I'm on a rarely-used backup machine, and the Update option didn't warn me about any compatibility issues. 

I have **not** restarted the browser after updating – not yet, need to keep multiple tabs open for a couple more days. Grateful for any help in restoring the keyboard shortcuts!

**Comment by rthaut** [comment]
Oh no!

As far as I know, that is not a known issue. I just tested it myself, and it works on the 2 systems I had quick access to (both Windows 10 running Firefox 95). It even moves in 5 second intervals for me.

I do not have access to a Mac system to do any testing of my own, but I could spin up a VM to try Firefox 73 on Windows when I have some time.

That said, the player itself is just YouTube's embedded player, so offhand I think it would be worth checking if embedded videos on regular pages work as expected or not, if you don't mind.

You can use the [YouTube Player Demo](https://developers.google.com/youtube/youtube_player_demo), or any webpage that has an embedded video.

The other option might be to try downgrading to an [older version](https://addons.mozilla.org/en-US/firefox/addon/youtube-popout-player/versions/); I think you can do that without needing to restart, though you may have to completely uninstall the extension first.

**Comment by mQkatz** [comment]
Hello @rthaut: Arrow keys **do** still give me the expected 5-second jump on other embedded videos. And restarting Firefox did **not** restore that behavior in YouTubePopoutPlayer.

But by maintaining that archive page of previous versions for downgrading – you're now my favorite extension developer. Something there should work. I'll either check the well-behaved version # on my 2 other Macs, or just take a guess and reinstall some ~3.x version here.

So, many thanks for your help here, for the older-versions archive, and for a great extension!

---

Only one other thing would make me even happier – and I don't see this in open or closed issues: Have you considered/investigated leaving Firefox's full menu bar available when the pop-out has focus? Currently, the player removes all menu headings except the **Firefox** menu. I'm not sure whether that's a design choice, a technical constraint, or a Mac OS accident. But it imposes a productivity hit when users need to do anything else in Firefox. We can't just click the menu bar to restore the other menu headings – first, we have to click on a tab **other** than the (empty) tab hosting the popped-out video.

Thanks again!

**Comment by rthaut** [comment]
> Only one other thing would make me even happier – and I don't see this in open or closed issues: Have you considered/investigated leaving Firefox's full menu bar available when the pop-out has focus? Currently, the player removes all menu headings except the **Firefox** menu. I'm not sure whether that's a design choice, a technical constraint, or a Mac OS accident. But it imposes a productivity hit when users need to do anything else in Firefox. We can't just click the menu bar to restore the other menu headings – first, we have to click on a tab **other** than the (empty) tab hosting the popped-out video.

This is a by-product of #23, where I had received a plethora of requests to hide the address bar and navigation buttons in early versions. Unfortunately, the window that gets created can either be a normal/standard window (with the title bar, address bar, menu bar, bookmark bar, etc.) or a "popup" window with just the title bar (based on functionality in the browser APIs).

On Mac OS I can see how that would be problematic;, though. I can't have it "switch" window types based on focus, and given how the window would (possibly significantly) resize to show/hide all of the various controls, I don't think that would be acceptable, even if it were possible.

However, would having it open as a normal window (configurable to the user through a new setting, of course) be acceptable, or would having to show **all** of the Firefox window elements negate the benefit of getting the menu bar? If that seems like a useful feature, feel free to open a new issue with a request to make the window type configurable.

As for the arrow keys, please provide an update if/when you find out more. The other thing to consider, however unlikely, is that the arrow keys may not work in Mac OS on the "popup" window type, given your testing seems to indicate the embedded player in normal windows works as expected. If that were the case, I don't think I could solve that issue within the extension (short of trying to hijack those key-presses to manually control playback), but that might be another reason to allow the user to change from the "popup" window type to a normal window type.

**Comment by mQkatz** [comment]
First, thanks for being responsive and making users happy! To answer your question, the behavior I'm really looking for is like this widget – which seems to be native to either YouTube or Firefox?:
![image](https://user-images.githubusercontent.com/12901606/150672186-6088b5dc-74f6-41cf-b2cc-8cc7457cebd3.png)

That opens a player window with only the chrome shown here:

![image](https://user-images.githubusercontent.com/12901606/150672316-28b12ec3-18af-4fb8-a2ff-d66e9d6dff46.png)

But the advantage isn't the chrome. It's that this is a completely independent window, which leaves Firefox's menu bar untouched. And once it's open, the user can even close the original page, meaning one less tab in the way. Another nice features is how it rewinds the video back a couple of seconds before the time point where the new window was spawned, to provide a buffer.

Its two significant disadvantages are: It evidently doesn't support YouTube's autoplay-related-videos option. Also, it has no apparent "always-on-top" option, which is a problem on small screens like this backup laptop's.

So this is where your extension is very handy. My ideal pop-out would do all 3 things: Leave the browser's menu bar intact, support autoplay chaining, and support always-on-top. But I'm not sure whether that's technically feasible.

I'll update you on this issue #368 after I'm back with my newer Macs this week. Arrow keys worked fine there, so I suspect that what I blundered into here is a Firefox 73 incompatibility issue. Thanks again.

**Comment by mQkatz** [comment]
Confirmed: Arrow keys work fine on this combination: 

- YouTubePopoutPlayer v.3.1.1
- Firefox 89.0.2
- Mac OS 10.15.3 (Catalina). 

And the interval **does** appear to be YouTube's standard 5 sec. jump per press. I'll update this comment later with the working combination on my other Mac (earlier Firefox and OS versions).

**Comment by mQkatz** [comment]
Arrow keys fail with this combination:

- YouTubePopoutPlayer 4.0.0
- Firefox 78.0.2 
- Mac OS 10.14.6 (Mojave)

**Comment by rthaut** [comment]
@mQkatz thank you for the continued investigation and detailed findings!

**Comment by mQkatz** [comment]
@rthaut One other possibility is that one of my many pop-up blockers is interfering with this extension. E.g., when I enable the "Advanced" UI in version 4.1.0 – nothing new actually shows up. I'll continue Sherlocking and report back. Thx.
