### ISSUE TITLE
PLease add allway on top funtion

### ISSUE THREAD

**Issue by Hawking312** [rthaut/YouTubePopoutPlayer#411]
your work so great, I really love your app. But please add allway on top funtion, it keep me can working and can see lessons on youtube, etc. Thank you so much and sorry for my bad english

**Comment by rthaut** [comment]
This is not currently possible through the extension, but I have documented some options for ways to accomplish this using your Operating System and/or other programs: [FAQ: How do I make the popout player always stay on top of other windows?](https://rthaut.github.io/YouTubePopoutPlayer/faq#always-on-top)
