### ISSUE TITLE
"Read your browser history" Permission in Chrome

### ISSUE THREAD

**Issue by eliashdezr** [rthaut/YouTubePopoutPlayer#50]
Is this extension collection now information?

**Comment by rthaut** [comment]
> Is this extension collection now information?

No, **the extension does not collect any information**.

That is the message Chrome displays for the `tabs` permission, which is used for closing the original window when the corresponding option ("Close Original Window/Tab") is enabled. See the row for "tabs" on the [Chrome documentation for Permissions](https://developer.chrome.com/extensions/permission_warnings#permissions_with_warnings), which lists that exact message.

For reference, [Firefox reports this permission](https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions) as "Access browser tabs," which is much more concise than Chrome's message.

I will update the [permissions documentation page](https://rthaut.github.io/YouTubePopoutPlayer/permissions) soon to clarify this for Chrome.

**Comment by rthaut** [comment]
I'm going to close this for now.

Between only requesting the `tabs` permission when needed now (per #55) and the updated documentation, I think the concern has been addressed.

That said, please feel free to update this ticket if any concern(s) remain.
